on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment:
        description: "Choose environment"
        default: "dev"
        required: true
        type: choice
        options:
          - dev

jobs:

  deployment:
    name: To BTP
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: CF Deploy
      id: deploy
      uses: ./.github/actions/cf-deploy
      with:
        createspace: false
        mtafile: ${{ inputs.mtar-dir }}/${{ inputs.mtar-file }}
        findurl_command: 'cf html5-list -di sflight-destination-service -u'

